version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers: # Optional
      - "kirbah"
    labels: # Optional
      - "ci"
      - "dependabot"
    commit-message: # Optional
      prefix: "chore(actions)"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly" # Consider "daily" if preferred
    reviewers: # Optional
      - "kirbah"
    labels: # Optional
      - "dependencies"
      - "dependabot"
    commit-message: # Optional
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
